- src/GeoParams.jl
- src/aliases.jl
- test/test_Density.jl
Included the possibility to set names aliases for methods used to compute different parameters.
> added macro to set aliases for functions to compute different parameters

- docs/make.jl
- docs/src/man/elasticity.md
- src/Computations.jl
- src/Elasticity/Elasticity.jl
- src/Plasticity/Plasticity.jl
- test/test_Elasticity.jl
- test/test_Plasticity.jl
This slightly updates the elasticity & plasticity implementation (simplifying it and adding fluid pressure). It also adds the comments of Albert on the previous PR (which was merged too quickly)
> Elasticity & Plasticity - 2 

- src/GeoParams.jl
- src/SeismicVelocity/SeismicVelocity.jl
- test/test_SeismicVelocity.jl
This updates the seismic velocity calculations & adds Vp/Vs calculations
> seismic velocities

- src/SeismicVelocity/SeismicVelocity.jl
Improve the performance of `anelastic_correction()` by ~60% with few changes in floating point operations.
> Improve performance of anelastic_correction()

- Project.toml
- src/CompositeRheologies.jl
- src/GeoParams.jl
This PR improves [#56](https://github.com/JuliaGeodynamics/GeoParams.jl/pull/56). I realised it made no sense to conditionally load CUDA and add it as a dependency.
> Adm-improve-#56

- docs/src/man/plotting.md
- docs/src/man/strengthenvelope.md
- src/Plotting/StrengthEnvelope.jl
- src/StrengthEnvelope/StrengthEnvelope.jl
Realized that documentation that is in the plotting routines will never be build so I moved it to a different file so it actually shows up. Hopefully this is the last one. The documentation does unfortunately not build on the fork. So I have to keep trying with pull requests.
> Another attempt to improve documentation

- src/CompositeRheologies/CompositeRheology.jl
- src/CreepLaw/CreepLaw.jl
- src/CreepLaw/DiffusionCreep.jl
- src/CreepLaw/DislocationCreep.jl
- src/Density/Density.jl
- src/Elasticity/Elasticity.jl
- src/Energy/Conductivity.jl
- src/Energy/HeatCapacity.jl
- src/Energy/LatentHeat.jl
- src/Energy/RadioactiveHeat.jl
- src/Energy/Shearheating.jl
- src/GravitationalAcceleration/GravitationalAcceleration.jl
- src/MeltFraction/MeltingParameterization.jl
- src/TensorAlgebra/TensorAlgebra.jl
Removes a large number of type annotations that are not really needed.
> Clean type annoations

- src/CompositeRheologies/CompositeRheology.jl
- src/ConstitutiveRelationships.jl
- src/CreepLaw/DiffusionCreep.jl
- src/CreepLaw/DislocationCreep.jl
- src/MaterialParameters.jl
- src/Viscosity/Viscosity.jl
Improves performance of viscosity calculations by ~10%.
> Performance of viscosity kernels

- src/MeltFraction/MeltingParameterization.jl
- test/test_MeltingParam.jl
- Evaluate the 4th and 5th polynomials using Horner's rule.
- Compute the ugly `dϕdT` derivatives of `SmoothMelting` with AD, much faster in my machine.
> Improve melt fraction calculations

- docs/make.jl
- docs/src/man/plasticity.md
- docs/src/man/viscosity.md
- src/Viscosity/Viscosity.jl
Add docs to `compute_viscosity_**` functions.
> add docs for compute viscosity functions

- src/Density/Density.jl
Adds some 3-4% speed up in pressure- and temeperature-dependant density by adding missing inlining macros and using fma's for the actual computation.
> Minor improvements on density calculations

- src/MeltFraction/MeltingParameterization.jl
Fixes the issue reported by @bkaus regarding the melting parameterization kernels not working on GPUs.
The following example should be working now:
```julia
using ParallelStencil
@init_parallel_stencil(CUDA, Float64, 2)
using GeoParams
MatParams     = (
SetMaterialParams(Name="Rock & partial melt", Phase=1, 
Density    = ConstantDensity(ρ=2700kg/m^3),                # used in the parameterisation of Whittington 
LatentHeat = ConstantLatentHeat(Q_L=3.13e5J/kg),
RadioactiveHeat = ExpDepthDependentRadioactiveHeat(H_0=1e-6Watt/m^3),
Conductivity = T_Conductivity_Whittington(),                 # T-dependent k
HeatCapacity = T_HeatCapacity_Whittington(),                 # T-dependent cp
Melting = SmoothMelting(MeltingParam_Quadratic())),                    # Quadratic parameterization as in …
```
> Fix melting kernels for GPUs

- src/ConstitutiveRelationships.jl
- src/GeoParams.jl
- src/Plasticity/DruckerPrager.jl
- src/Plasticity/DruckerPrager_regularised.jl
- src/Softening/Softening.jl
- test/test_Softening.jl
And fixes bug that was causing a segmentation fault
> Renames `NoLinearSoftening`

- Project.toml
- src/CreepLaw/MeltViscosity.jl
- src/Density/Density.jl
- src/Energy/HeatCapacity.jl
- test/test_CreepLaw.jl
- test/test_Density.jl
- test/test_DiffusionCreep.jl
- test/test_DislocationCreep.jl
- test/test_Energy.jl
- test/test_GrainBoundarySliding.jl
- test/test_MeltingParam.jl
- test/test_NonLinearPeierlsCreep.jl
- test/test_PeierlsCreep.jl
- test/test_Softening.jl
This fixes several `isbits` errors for newer structs
> fixes `isbits` error

- src/Computations.jl
Reverts JuliaGeodynamics/GeoParams.jl#179
> Revert "relax type restriction in compute_param!"

- docs/src/man/TASclassification.md
- docs/src/man/conductivity.md
- docs/src/man/creeplaws.md
- docs/src/man/customrheology.md
- docs/src/man/density.md
- docs/src/man/elasticity.md
- docs/src/man/gravity.md
- docs/src/man/heatcapacity.md
- docs/src/man/latentheat.md
- docs/src/man/melting.md
- docs/src/man/nondimensionalize.md
- docs/src/man/plasticity.md
- docs/src/man/radioactiveheating.md
- docs/src/man/seismicvelocity.md
- docs/src/man/shearheating.md
- docs/src/man/viscosity.md
- docs/src/man/zirconages.md
Cleans up the docs from the mising docstring warning and adds a couple of small updates.
> Clean up docs

- src/Elasticity/Elasticity.jl
- src/GeoParams.jl
- src/Traits/rheology.jl
- test/test_Elasticity.jl
- test/test_Traits.jl
Adds `ElasticRheologyTrait` and `NonElasticRheologyTrait` traits and extends `get_G` and `get_Kb` to work with `CompositeRheology`.
> Add ViscoElastic trait and extend get_G and get_Kb

- src/GeoParams.jl
- test/test_Traits.jl
> Bugfix in `get_Kb`

- src/GravitationalAcceleration/GravitationalAcceleration.jl
- test/test_Gravity.jl
Fixes small bug introduced by #229
> Fix bug & expand tests of `DippingGravity`

- .github/workflows/Downstream.yml
In this file we can add repos that are directly dependent on GeoParams and let the CI tests for the specified pkg run
> Add a downstream pipeline for testing

- docs/make.jl
- docs/src/man/permeability.md
- src/Permeability/Permeability.jl
Adds a doc page for permeability as requested by @boriskaus
> Documentation for Permeability

- src/Computations.jl
- src/Elasticity/Elasticity.jl
- src/Energy/Shearheating.jl
- src/GeoParams.jl
- src/PhaseDiagrams/PhaseDiagrams.jl
- src/Plasticity/DruckerPrager.jl
- src/Plasticity/DruckerPrager_regularised.jl
- src/Plasticity/Plasticity.jl
- src/Rheology_Utils.jl
- src/SeismicVelocity/SeismicVelocity.jl
- src/Softening/Softening.jl
- src/StressComputations/StressComputations.jl
- src/TensorAlgebra/TensorAlgebra.jl
- src/Traits/rheology.jl
- src/Units.jl
- src/Utils.jl
- src/Viscosity/Viscosity.jl
- test/Project.toml
- test/test_Aqua.jl
This PR adds some quality control tests using Aqua. I solved many of the issues it raised, e.g. undefined exports, ambiguities, unbounds args... Some tests continue to fail but may be hard to fix at this state.
> Add Aqua to tests

- src/Units.jl
> Fix bug when printing GeoUnits on the REPL

- src/Units.jl
- test/test_CompositeRheologies.jl
- test/test_Elasticity.jl
- test/test_GeoUnits.jl
- test/test_GrainBoundarySliding.jl
- test/test_NonLinearPeierlsCreep.jl
- test/test_PeierlsCreep.jl
- test/test_Permeability.jl
- test/test_Plasticity.jl
Fix bug in #257 and add few tests for custom `show `methods
> Fixes #257

- src/Plotting/Plotting.jl
Updates the `Plot_TAS_diagram` to plot the TAS polygons and compositions on top. Composition has to be an Array.
> Update TAS  Diagram plotting

- src/CreepLaw/GrainBoundarySliding.jl
Addresses problem (1) raised in #273
> Remove comment from `math` markdown

- docs/make.jl
- docs/src/index.md
- docs/src/man/Melt.md
> fix typo in docs
