JuliaGeodynamics/GeoParams.jl

- src/CreepLaw/DislocationCreep.jl
- src/Units.jl
- test/test_DislocationCreep.jl
Currently `computeCreepLaw_EpsII()` and `computeCreepLaw_TauII()` take the argument `p::CreepLawVariables`. To use these routines with [ParallelStencil.jl](https://github.com/omlins/ParallelStencil.jl) it's better to have a bit less abstraction. This PR adds a couple of methods `computeCreepLaw_EpsII()` and `computeCreepLaw_TauII()` where the arguments `P,T,f` are `Real` numbers instead of being inside `CreepLawVariables`. The corresponding test file is also fixed.
> New methods for dislocation creep laws and fix test_DislocationCreep.jl

- src/Computations.jl
Add type signatures to force specializations on `compute_param()` methods.
> Force specialization

- docs/src/man/seismicvelocity.md
- src/GeoParams.jl
- src/SeismicVelocity/SeismicVelocity.jl
- test/test_SeismicVelocity.jl
The routine uses the reduction formulation of Clark et al., (2017) and is based on the equilibrium geometry model for the solid skeleton of Takei et al., 1998.
> Seismic velocity correction for melt fraction

- docs/src/man/seismicvelocity.md
- src/GeoParams.jl
- src/SeismicVelocity/SeismicVelocity.jl
- test/test_SeismicVelocity.jl
Ths routine is based on the equilibrium geometry model for the solid skeleton of Takei et al. (1998) and the porosity-depth empirical relationship of Chen et al. (2020)
> Seismic S-wave velocity correction for (shallow depth) porosity

- src/Computations.jl
- src/GravitationalAcceleration/GravitationalAcceleration.jl
This fixes the problem where a call like this `compute_gravity(MatParam[Phases[i,j]].Gravity[1])` is type-unstable. The new type-stable method can now be called as  `compute_gravity(MatParam, Phases[i,j])`.
> Method to compute gravity given material phases

- src/Computations.jl
Fix type instability in [here](https://github.com/JuliaGeodynamics/GeoParams.jl/blob/a81bf559b8ed6e9f42920210af3bb6c2cfbd6689/src/Computations.jl#L25) which led to a 40% performance drop.
> type instability

- src/Plasticity/Plasticity.jl
Trigonometric functions are expensive and the `sind` and `cosd`  calls on the friction and dilation angles can be precomputed within the plasticity struct. This removes a lot of redundant compute time:
```julia
a=DruckerPrager()
julia> @btime $a() # trigs not precomputed
17.735 ns (0 allocations: 0 bytes)
-8.660254037844386e6
julia> @btime $a() # trigs precomputed
2.000 ns (0 allocations: 0 bytes)
-8.660254037844386e6
```
> Precompute trigonometric functions

- Project.toml
- src/CompositeRheologies.jl
- src/GeoParams.jl
`println()` does not work in CUDA kerneles. This PR conditionally loads CUDA with `Requires` and switches off all the calls to `println` when CUDA has been loaded.
> Remove println() calls when CUDA is active

- docs/make.jl
- docs/src/man/plotting.md
- docs/src/man/strengthenvelope.md
- src/Plotting/StrengthEnvelope.jl
- src/StrengthEnvelope/StrengthEnvelope.jl
- test/test_StrengthEnvelope.jl
Sorry for another one but I forgot to add some stuff to the documentation when I split the function in two.
I also renamed the temperature functions that are stolen from GeophysicalModelGenerator so that there are no conflicts when loading both packages
> Documentation fixes

- src/TensorAlgebra/TensorAlgebra.jl
- test/Project.toml
- test/test_TensorAlgebra.jl
Fix some bugs for the computation of the second invariant of a 3D symmetric tensor in staggered grids.
> Second invariants

- src/CompositeRheologies/NonlinearIterations.jl
- src/ConstitutiveRelationships.jl
- src/Utils.jl
Checking if CUDA is active is really slow and dominates the total time spend in the local iteration kernels.
This PR removes all the redundant checks and considerably speeds up these kernels:
```julia-repl
@btime computeViscosity_εII($v, $ε̇ii, $args) 
310.163 ns (0 allocations: 0 bytes)
@btime computeViscosity_εII($v, $ε̇ii, $args) 
83.126 ns (0 allocations: 0 bytes)
```
> Remove redundant CPU checks

- src/Units.jl
- test/test_GeoUnits.jl
Very simple PR that allows nondimensionalising Tuples of dimensional parameters, to shorten user codes:
```Julia
julia> g=GEO_units();
julia> a,b = nondimensionalize((100km, 800/s),g)
(100 km, 800 s⁻¹·⁰)
```
> nondimensionalize tuples

- src/ConstitutiveRelationships.jl
- src/Elasticity/Elasticity.jl
- src/GeoParams.jl
- test/test_Elasticity.jl
Convinience methods to extract the shear and bulk modulus from `ConstantElasticity`
```julia
a = ConstantElasticity()
v = SetMaterialParams(; Elasticity = ConstantElasticity())
vv=(
SetMaterialParams(; Phase=1, Elasticity = ConstantElasticity()),
SetMaterialParams(; Phase=2, Elasticity = ConstantElasticity()),
)
get_G(a) == a.G.val
get_G(v) == a.G.val
get_G(vv, 1) == get_G(vv, 2) == a.G.val # for multiple phases
get_Kb(a) == a.Kb.val
get_Kb(v) == a.Kb.val
get_Kb(vv, 1) == get_Kb(vv, 2) == a.Kb.val # for multiple phases
```
> Extract elastic parameters from MaterialParams

- src/Density/Density.jl
- src/GeoParams.jl
- test/test_Density.jl
There was an in-place function `compute_density!(rho, Mat_tup1, PhaseRatio, args)` to do this but we are missing the one to do it locally, which is more convinient for our codes. To avoid name redunancy and ambiguity, I think it is better to use a different name for local volume fractions kernels, e.g. `compute_density_ratio(PhaseRatio, rheologies, args)` here.
> Local density function for multi-phases rheology given volume fractions

- src/Computations.jl
Make `compute_param_times_frac` compatible with `StaticArrays` so that it works with `CellArrays.jl`
> compute_param_times_frac compat with CellArrays

- src/Viscosity/Viscosity.jl
Fixes bug from #91, where it was crashing if there was an `AbstractPlasticity` in the `CompositeRheology`.
> Fix bug for rheologies with plasticity

- src/Computations.jl
- src/Viscosity/Viscosity.jl
- test/test_Density.jl
Extends `compute_param` to work with phase ratios given by `Ntuple`s and `StaticArrays` (i.e. compatible with `CellArrays`). Example:
```julia
using Test, GeoParams, StaticArrays
args = (P=0.0, T=20.0)
rheologies = (
SetMaterialParams(;
Name="Crust",
Phase=0,
CreepLaws=(PowerlawViscous(), LinearViscous(; η=1e23Pas)),
Density=ConstantDensity(; ρ=2900kg / m^3),
),
SetMaterialParams(;
Name="Lower Crust",
Phase=1,
CreepLaws=(PowerlawViscous(; n=5.0), LinearViscous(; η=1e21Pas)),
Density=Compressible_Density(; ρ0=3000kg / m^3),
)
)
PhaseRatio = (0.5, 0.5)
@test 2950e0 == compute_density(rheologies, PhaseRatio, args)
SvPhaseRatio = SA[0.5, 0.5]
@test 2950e0 == compute_density(rheologies, SvPhaseRatio, args)
```
> Local compute_param methods for phase ratios

- .github/dependabot.yml
- .github/workflows/SpellCheck.yml
- .typos.toml
- src/CompositeRheologies/CompositeRheologies_print.jl
- src/Computations.jl
- test/test_GeoUnits.jl
This setup will run a spell checker for every PR. I fixed the version of the spell checker to avoid letting PRs fail due to updates of it. Dependabot will automatically create PRs with updates of the spell checker. To reduce their frequency, I set up Dependabot to run monthly instead of weekly.
If you like this, we can set it up for other repos as well.
> fix typos and add spell check

- src/Plotting/Plotting.jl
Ports the two remaining plotting functions in `src/Plotting/Plotting.jl` from `Plots.jl` to `Makie.jl`. 
Closes #104
New TAS diagram with Makie.jl
> Port all the figures to Makie.jl

- src/Viscosity/Viscosity.jl
Fixes bug where `compute_viscosity_τII(v, phase_ratio, args)` was always returning 0.0.  
`phase_ratio` can also be a `SVector` now, so that it is compatible with `CellArrays.jl`.
> Fix bug in viscosity calculations for multiple rheology phases

- src/ConstitutiveRelationships.jl
- src/CreepLaw/DiffusionCreep.jl
- src/CreepLaw/DislocationCreep.jl
- src/Utils.jl
Powers with floating point exponents are quite slow, and this is where mos of the time is spent when computing the stress rate or deviatoric stress of creep laws. However, in many cases the exponentials in these equations are just `x^0`, `x^1` or `1^n`, where there is not really a need to compute the power. Addresses #109 
This PR adds a check to see whether any of these cases occurs, by introducing:
```julia
@inline function pow_check(x::T, n) where T
if isone(x) || isone(n)
x
elseif iszero(n)
one(T)
else
fastpow(x, n)
end
end
```
in all the `compute_εII` and `compute_τII` methods. 
This has a non-significant speed up when e.g. computing the viscosity:
```julia
εII = 1e-15
τII = 1e6
P, T = 1e9, 1e3;
args = (; P = P, T = T);
diff     = DiffusionCreep()
disl     = DislocationCreep() …
```
> Speeding up strain rate and deviatoric stress kernels

- src/CreepLaw/Data/DiffusionCreep.jl
- src/CreepLaw/Data/DislocationCreep.jl
- src/CreepLaw/Data/GrainBoundarySliding.jl
- src/CreepLaw/Data/NonLinearPeierlsCreep.jl
- src/CreepLaw/Data/PeierlsCreep.jl
- test/test_DiffusionCreep.jl
- test/test_GrainBoundarySliding.jl
- test/test_NonLinearPeierlsCreep.jl
- test/test_PeierlsCreep.jl
- test/test_Viscosity.jl
This PR adds an option to directly non-dimensionalize power laws dfined in the database. It's enough to pass the characteristic lenghts when instantiating the rheology struct.
```julia
CharDims = GEO_units(; viscosity=1e19, length=1000km)
SetDiffusionCreep("Dry Anorthite | Rybacki et al. (2006)", CharDims)
```
> Non-dimensionalization of pre-defined power laws

- src/Units.jl
- test/test_GeoUnits.jl
```julia
function foo()
g = CharUnits_GEO = GEO_units(; viscosity=1e19, length=1000km)
x = SetMaterialParams(;
Name="test1",
Phase=22,
CreepLaws=(PowerlawViscous(), LinearViscous(; η=1e21Pa * s)),
Gravity=ConstantGravity(; g=11.0m / s^2),
Density=ConstantDensity(),
)
x_nd = nondimensionalize(x, CharUnits_GEO)
y = SetMaterialParams(;
Name="test1",
Phase=22,
CreepLaws=(PowerlawViscous(), LinearViscous(; η=1e21Pa * s)),
Gravity=ConstantGravity(; g=11.0m / s^2),
Density=ConstantDensity(),
CharDim = CharUnits_GEO
)
a, b, c = 0, 0, 0
ta, tb, tc = 0, 0, 0
for _ in 1:1_000_000
ta += @elapsed begin a += @allocated begin compute_density(x_nd, (;)) end end
tb += @elapsed begin b += @allocated begin compute_density(x, (;)) end end
tc += @elapsed begin c += @allocated begin compute_density(y, (;)) end …
```
> Fix allocations from non/dimensionalizing MatParamStructs

- src/GeoParams.jl
The docstring was not attach directly to the module, so it wasn't found. I removed the `__precompile__()` call since it was just using the default setting (precompilation enabled), so it didn't have any other effect than removing the docstring.
> fix docstring of GeoParams

- Project.toml
- README.md
- docs/src/man/TASclassification.md
- docs/src/man/melting.md
- docs/src/man/zirconages.md
- ext/GeoParamsGLMakieExt.jl
- src/Energy/Conductivity.jl
- src/GeoParams.jl
- src/MeltFraction/MeltingParameterization.jl
- src/Plotting/Plotting.jl
- src/Plotting/StrengthEnvelope.jl
I updated the optional plotting code from Requires.jl to package extensions for newer Julia versions. I kept backwards compatibility by still using Requires.jl for old Julia versions. This cuts the loading time `using GLMakie, GeoParams` for me by something between 0.5 and 1.5 seconds. However, there is still a lot of recompilation left, so this should be investigated in the future.
Caveats:
- I did not test this - except checking that `using GLMakie, GeoParams` works on Julia v1.8 and v1.9. I do not know whether the plotting routines are tested in CI (see #103) but I will assume that everything is fine if CI passes.
- There are still some remnants of a previos version using Plots.jl (see #104). I did not update them to GLMakie.jl.
> Use a package extension for GLMakie-based functionality

- src/Units.jl
- test/test_GeoUnits.jl
This fixes issue #125 which pointed out a bug in operations on non-dimensional GeoUnits (reported by @aelligp)
```julia
using GeoParams
CharDim    = GEO_units(length=40km, viscosity=1e20Pa*s);
T = GeoUnit(100K)
T_nd = nondimensionalize(T, CharDim)
```
Before:
```julia
julia> T_nd*T_nd
GeoUnit{nondimensional, }, 
0.006169370482479428
```
After:
```julia
julia> T_nd*T_nd
GeoUnit{nondimensional, K²·⁰}, 
0.006169370482479428
```
> Bugfix for operations on nondimensional GeoUnits

- src/GeoParams.jl
- src/MeltFraction/MeltingParameterization.jl
- test/test_MeltingParam.jl
This provides the same framework for melt fraction as for density and utilises `compute_param_times_frac`.
> compute melt fraction with PhaseRatios

- src/Viscosity/Viscosity.jl
- test/test_Viscosity.jl
Fixes the bug in `compute_elastoviscosity_εII` reported in #132
> Effective viscosity bug

- src/Energy/Shearheating.jl
- test/test_Energy.jl
Improves performance for tensors of type `NTuple` and fixes broken [in-place method](https://github.com/JuliaGeodynamics/GeoParams.jl/blob/3033d3f6e70a76fb7408cabb22c8a9ea719c68fe/src/Energy/Shearheating.jl#L49).
> Shear heating

- src/Elasticity/Elasticity.jl
- test/test_Elasticity.jl
Using nothing for `G` and `ν` makes `SetConstantElasticity()` without any input arguments produce `NaN`s. To fix that default values without Units are set.
> set default values for G and nu in SetConstantElasticity()

- src/Units.jl
- test/test_Density.jl
- test/test_Energy.jl
Fixes the type instabilities in  `compute_units` which had an impact in the non/dimensionalization functions.
```julia
CharUnits_GEO = GEO_units(; viscosity=1e19, length=1000km)
```
Main branch
```julia-repl
julia> @btime nondimensionalize($(10cm / yr, CharUnits_GEO)...)
4.827 μs (66 allocations: 2.69 KiB)
```
This PR
```julia-repl
julia> @btime nondimensionalize($(10cm / yr, CharUnits_GEO)...)
161.724 ns (5 allocations: 80 bytes)
```
The remaining allocations are because `GeoUnits` is not parameterized ([here](https://github.com/JuliaGeodynamics/GeoParams.jl/blob/a21703cb285cf07479e3023677d21827b67f9f29/src/Units.jl#L312)). I'm not sure it's worth the effort though.
> Fix instabilities in `compute_units`

- src/Energy/Shearheating.jl
- test/test_Energy.jl
Fixes a bug when a tuple with the tensors in Voigt notation was passed into the 3D shear heating kernel.
This PR also expands the shear heating test coverage.
> Fixes bug id 3D shear heating kernel

- src/Softening/Softening.jl
- test/test_Softening.jl
And improves a bit the related testing
> Fix softening bug

- src/ConstitutiveRelationships.jl
- src/GeoParams.jl
- src/Softening/Softening.jl
Adds non linear softening from [Thibault et al 21](https://agupubs.onlinelibrary.wiley.com/doi/pdfdirect/10.1029/2021GC009675)
> Non linear softening

- docs/src/man/latentheat.md
- src/Energy/Conductivity.jl
- src/Energy/HeatCapacity.jl
- src/Energy/LatentHeat.jl
- src/GeoParams.jl
- test/test_Energy.jl
There are two ways to implement latent heat in the energy equation: explicitly by adding it as a source term or implicitly. The explicit manner was already available `GeoParams`; this PR adds the implicit method which implements it by modifying the thermal heat capacity (making it temperature-dependent).
The are several texts on how to implement this; since some lessons learned seemed to have gone forgotten, I recently summarised this [here](https://pubs.geoscienceworld.org/gsa/geosphere/article/19/4/1006/624461/Zircon-age-spectra-to-quantify-magma-evolution).
In short, the energy equation (w/out advection) is:
```math
\rho c_p \frac{\partial T}{\partial t}  ) = \frac{\partial }{\partial x_i} \left( k   \frac{\partial T}{\partial x_i}  \right)  + H_s + \rho Q_L\frac{\partial …
```
> Add latent heat by modifying heat capacity 

- src/Energy/HeatCapacity.jl
Fixes the bug caused by not having `dϕdT` in the args when calling `Latent_HeatCapacity`:
```julia
x = Latent_HeatCapacity(Cp=ConstantHeatCapacity(), Q_L=400kJ/kg)
a = (; T = 10e0) 
compute_heatcapacity(x, a)
```
would throw
```julia-repl
In [13]: compute_heatcapacity(x, a)
ERROR: MethodError: no method matching precision(::Latent_HeatCapacity{Float64, Unitful.FreeUnits{(kg^-1.0, kJ), 𝐋^2.0 𝐓^-2.0, nothing}}  
)
Closest candidates are:
precision(::BigFloat; base)
@ Base mpfr.jl:898
precision(::ForwardDiff.Dual; base)
@ ForwardDiff C:\Users\albert\.julia\packages\ForwardDiff\PcZ48\src\dual.jl:303
precision(::Type{D}; base) where D<:ForwardDiff.Dual
@ ForwardDiff C:\Users\albert\.julia\packages\ForwardDiff\PcZ48\src\dual.jl:304
...
Stacktrace:
[1] compute_heatcapacity
@ …
```
> Fixes bug in `Latent_HeatCapacity`

- src/ConstitutiveRelationships.jl
- src/Density/Density.jl
- src/Elasticity/Elasticity.jl
- src/Energy/Conductivity.jl
- src/Energy/Energy.jl
- src/Energy/HeatCapacity.jl
- src/Energy/RadioactiveHeat.jl
- src/Utils.jl
- test/test_Density.jl
- test/test_Energy.jl
Sometimes I need to extract parameters from different types which they may be inside tuples of different phases or whatever. This PR adds the `@extractors` macro to automatically generate functions to extract variables from a `struct`. An example for the `AbstractDensity` case [here](https://github.com/JuliaGeodynamics/GeoParams.jl/blob/04bcbfdc030b9aec5a6c5564ca6c0ff00fdac181/src/Density/Density.jl#L375-L379)
```
for type in (ConstantDensity, PT_Density, Compressible_Density, T_Density, MeltDependent_Density)
@extractors(type, :Density)
end
```
generates e.g. `get_α(x::PT_Density) = x.α.val` and the appropriate methods for `AbstractMaterialParamsStruct` and `Tuple{N, AbstractMaterialParamsStruct}`. 
In action:
```julia-repl
In [1]: using GeoParams
In [1]: x = PT_Density()
P/T-dependent …
```
> Extractor methods

- src/GeoParams.jl
- src/Viscosity/Viscosity.jl
- test/test_Viscosity.jl
Introduces `compute_viscosity` function for `LinearViscous` and `ConstantElasticity` objects:
```julia
η0  = 3
dt  = 4
args = (; dt=dt)
G        = 1
el       = SetConstantElasticity(; G=G, ν=0.5)
creep    = LinearViscous(; η=η0)
rheology = SetMaterialParams(; CompositeRheology=CompositeRheology((creep, el)))
@assert compute_viscosity(el, args) == G * dt  # true
@assert compute_viscosity(creep, args) == η0 # true
@assert compute_viscosity(rheology, args) == 1/(1 / η0 + 1 / G / dt) # true
```
`compute_elasticviscosity` can be used to compute `G * dt`
```julia
rheologies2 = (
SetMaterialParams(; 
CompositeRheology=CompositeRheology((LinearViscous(; η=1), el))
),
SetMaterialParams(; 
CompositeRheology=CompositeRheology((LinearViscous(; η=2), el))
)
)
@assert …
```
> Viscosity methods for linear rheologies

- codecov.yaml
there was an addtional space in the `codecov.yaml` prohibiting the upload
> fixes codecov

- src/Density/Density.jl
- src/Energy/HeatCapacity.jl
- src/GeoParams.jl
- src/MeltFraction/MeltingParameterization.jl
- test/test_Density.jl
- test/test_Energy.jl
- test/test_MeltingParam.jl
This PR allows specifying vectors with `Density`, `HeatCapacity` and `MeltFraction` data and retrieving them with indices.
> Vector density, melt fraction and heat capacity 

- src/CompositeRheologies/NonlinearIterations.jl
- src/Plasticity/DruckerPrager.jl
- src/Plasticity/DruckerPrager_regularised.jl
Makes stress local iteration methods, as well as `DruckerPrager` and `DruckerPrager_regularised` compatible with, at least, `ForwardDiff.jl`
> Increase compatibility with AD tools

- src/Plasticity/DruckerPrager.jl
- src/Plasticity/DruckerPrager_regularised.jl
- test/test_Plasticity.jl
Adds a `pertubation_C` keyword for `DruckerPrager` and `DruckerPrager_regularized` so that the cohesion can be perturbation such that `C_perturbed = C * pertubation_C`
> Add perturbation kwarg to cohesion

- src/CreepLaw/MeltViscosity.jl
A couple of changes to get a ~20% performance boost when computing the viscosity of `ViscosityPartialMelt_Costa_etal_2009`
> Performance boost to `ViscosityPartialMelt_Costa_etal_2009`

- src/ConstitutiveRelationships.jl
- src/GeoParams.jl
- src/Plasticity/DruckerPrager.jl
- src/Plasticity/DruckerPrager_regularised.jl
- src/Softening/Softening.jl
- test/test_Softening.jl
With this PR we can mix up different available softening definitions for cohesion and friction angle. Also introduces a new decay softening based on strain rate similar to Taras' one
> Mixed softening and new law

- src/Energy/Shearheating.jl
- src/MeltFraction/MeltingParameterization.jl
fixes an issue with `compute_meltfraction` reported in JustRelax when running on the GPU. if `s.Melting` is empty it now returns `0e0` and not `zero(eltype(args).type[1])` anymore. 
- also updated number format for Shearheating (where we alreadt did the same as in melting)
> fix `compute_meltfraction`

- src/ConstitutiveRelationships.jl
- src/CreepLaw/CreepLaw.jl
- src/MeltFraction/MeltingParameterization.jl
- test/test_CreepLaw.jl
Power law creep had a `struct` already defined in `src/CreepLaw.jl`. However, there were no methods associated to it.
> Add power law strain/stress functions

- src/CreepLaw/Data/DislocationCreep.jl
In this PR, some of the Dislocation creep laws are corrected to the values stated in the corresponding papers. Checked through a list provided by @Dr3ven that initially set up the entire database. 
Also added 2 new laws by `Chopra & Paterson (1981)`
> Dislocation Creep law checked

- docs/src/man/gravity.md
- src/GeoParams.jl
- src/GravitationalAcceleration/GravitationalAcceleration.jl
- test/test_Gravity.jl
Adds a gravity field in a rotated Cartesian frame of reference. It may be useful for, e.g., modelling subduction channels.
> Add `DippingGravity` type

- src/Units.jl
- test/test_GeoUnits.jl
- test/test_MaterialParameters.jl
This PR adapts the (non-)dimensionalisation functions to also work if no characteristic unit is provided. It will return the original values without the units and adds a warning that char. units is not provided. 
This could be useful if a script is usually non-dimensional but one would like to try with dimensional numbers.
E.g.:
```julia-repl
julia> nondimensionalize(10cm/yr,nothing)
┌ Warning: The input parameter is not being nondimensionalized, as no characteristic units are given
└ @ GeoParams.Units ~/Documents/PhD/GeoParams.jl/src/Units.jl:610
10
julia> nondimensionalize(T, nothing)
┌ Warning: The input parameter is not being nondimensionalized, as no characteristic units are given
└ @ GeoParams.Units ~/Documents/PhD/GeoParams.jl/src/Units.jl:642
3×3 Matrix{Int64}:
10  10  10
10  10 …
```
> New functionality to nondimensionalisation

- docs/src/man/density.md
- src/Density/Density.jl
- src/GeoParams.jl
- src/MaterialParameters.jl
- test/test_Density.jl
This pull request introduces new density calculation models for magma densities in conduit flows. 
Defines the BubbleFlow_Density as described in Slezin (2003) with a default gas solubility constant of 0.0041MPa^{-1/2} used in e.g. Sparks et al. (1978)
```math
\rho = \frac{1}{\frac{c_0 - c}{\rho_g} + \frac{1-(c_0-c)}{\rho_m}}
```
with
```math
c =
\begin{cases}
aP^{1/2} & \text{for } P < \frac{c_0^2}{a^2} \\
c_0 & \text{for } P \geq \frac{c_0^2}{a^2}
\end{cases}
```
- `ρmelt`: Density of the melt
- `ρgas`: Density of the gas
- `c0`: Total volatile content
- `a`: Gas solubility constant (default: 0.0041MPa^{-1/2}) (after Sparks et al., 1978)
Possible values for a are 0.0032-0.0064MPa``^{-1/2}`` where the lower value corresponds to mafic magmas at rather large pressures (400-600MPa) and the …
> Conduit densities

- src/Units.jl
This PR Improves and simplifies the non dimensionalization of `AbstractMaterialParam`s, so that it does not rely on `Setfields.jl` anymore. This solves the problems reported by @Iddingsite in #241. It also slighlty improves the performance
```julia
using GeoParams
CharUnits_GEO = GEO_units(; viscosity=1Pa * s, length=1m)
x = DiffusionCreep()
```
This PR:
```julia-repl
julia> @benchmark nondimensionalize($x, $CharUnits_GEO)
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
Range (min … max):  1.470 μs …  18.470 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     1.620 μs               ┊ GC (median):    0.00%    
Time  (mean ± σ):   1.621 μs ± 307.944 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%
▁ ▅█▇ ▃           ▁ ▄▄ ▁
▂▃▄▁██▁███▁█▇▁▄▃▃▁▃▄▁▅▆█▁██▁█▆▅▁▅▄▁▅▅▅▁▅▄▁▃▃▃▁▃▂▁▂▂▂▁▂▂▁▂▂▂ ▃
1.47 μs …
```
> Improve non dimensionalization of `AbstractMaterialParam`s

- README.md
- docs/src/man/nondimensionalize.md
- src/GeoParams.jl
- src/Plotting/Plotting.jl
- src/Plotting/StrengthEnvelope.jl
- src/StrengthEnvelope/StrengthEnvelope.jl
- src/Units.jl
- test/test_StrengthEnvelope.jl
Supersed #244 (Too lazy to rebase for the Runic.jl changes).
> replace Myrs by Myr
